name: rtd
dependencies:
- alabaster=0.7.7=py35_0
- babel=2.2.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- docutils=0.12=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- ipython=4.1.2=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- llvmlite=0.9.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- mpmath=0.19=py35_0
- numba=0.24.0=np110py35_0
- numpy=1.10.4=py35_1
- numpydoc=0.5=py35_1
- openssl=1.0.2g=0
- pandas=0.18.0=np110py35_0
- path.py=8.1.2=py35_1
- patsy=0.4.0=np110py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.0=py35_0
- pygments=2.1.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.5.0=py35_0
- pytz=2015.7=py35_0
- qt=4.8.7=1
- readline=6.2=2
- requests=2.9.1=py35_0
- scipy=0.17.0=np110py35_2
- setuptools=20.2.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.9.2=0
- statsmodels=0.6.1=np110py35_0
- sympy=1.0=py35_0
- tk=8.5.18=0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - quantecon==0.3.1
  - sphinx-rtd-theme==0.1.9

